# Generated by Django 4.1.5 on 2023-01-22 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=256, unique=True, verbose_name="이메일"),
                ),
                ("is_admin", models.BooleanField(default=False, verbose_name="관리자")),
                ("is_active", models.BooleanField(default=True, verbose_name="권한")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="업데이트일"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
